deployment, autodeploy: init autodeploy.
starlingx-staging/tools-contrib pull request #3
Opened 2019-04-02 03:22 UTC by ychen2u

Initial version of autodeploy tool, version number 1.01.

Signed-off-by: chenyan <yan.chen@intel.com>

2019-04-02 16:02 UTC, saulwold requested changes
There are some internal references that need to be removed and the commit message needs to be more complete.

2019-04-02 21:17 UTC, ericho reviewed
Hi,

This is great and it has been a lot of work. The only _important_ comment I have is to remove the `--kubernetes` flag on `config_controller`. All the other comments are suggestions that can (if we decide so) be covered in other iterations.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/README.md
> +# akraino-qa
Maybe this is not needed.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/README.md
> +* Ubunto 16.04/18.04/18.10
Little typo in Ubuntu

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +dplmnt["hack"] = {}
What's the purpose of this setting?

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +         "99: check NIC name.",
This `99` starting point feels a little bit out of place for the `--start` argument. Maybe this could be a separate flag.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +    LOG.Info("!!! WARNING !!!: vbox is not tested in this version of script.")
Should the script stop at this point if vbox is selected?

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +        print("Waiting ... %s seconds left\r" % str(left))
You can use `LOG.Info` as is called in other places in this code.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +    except Exception, error:
I think this should be `except Exception as error:`

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +            return 0
If `DEBUG` is set, then it should do nothing? I'm thinking that this probably should be the opposite.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +                return int(result)
How the length of the result from the `temp_testresult` relates with a return code?

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +    LOG.Info("Please check the full system log.")
Maybe this message should point to where to look for system logs.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +                continue
I we can't ping a node in the list, this maybe should print a warning telling us that.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +    if 0 != result:
Just `if result:` works as well :)

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +with open(dplmnt["config"], 'r') as cfg:
Alternatively, you can use `ConfigParser.ConfigParser()` and save a lot of code here. There's a lot of examples out there on how to use this module, [this is how we are using it in the new download mirror tool](https://github.com/ericho/stx-tools/blob/mirror-dev/stx-mirror/stx_mirror/configuration.py#L20).

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +            LOG.Info("Step 3: Run \"sudo config_controller --kubernetes\" on controller")
This is not needed anymore.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/autodeploy.py
> +               " --kubernetes"
You can remove the `--kubernetes` option.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/cleanupdeploy.py
> +desc = "EC Auto Deployment - Cleanup"
What's "EC" in this context?

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/cleanupdeploy.py
> +def cmdhost(cmd, cwd=None, logfile=None, silent=False):
This function is repeated from `autodeploy.py`, it might need to be placed in a separate module/file.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/libvirt/setup_controller.sh
> +echo "createing $name with $iso"
Little typo

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/openstack_logcheck.py
> +# Parse the following log and return the dict for vmname.
We can consider the `--format csv` flag to get a machine readable format.

2019-04-02 21:17 UTC, ericho commented on deployment/autodeploy/prepare.sh
> +sudo ntpdate edgehost02.sh.intel.com
You can remove this

2019-04-03 01:45 UTC, ychen2u commented
> There are some internal references that need to be removed and the commit message needs to be more complete.
Thanks for review, I will clean up the internal references in one minute :P

2019-04-03 01:57 UTC, ychen2u commented on deployment/autodeploy/README.md
> +# akraino-qa
Thanks a lot!
I will remove it.

2019-04-03 01:58 UTC, ychen2u commented on deployment/autodeploy/README.md
> +* Ubunto 16.04/18.04/18.10
Thanks~ My bad~:D

2019-04-03 02:00 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +dplmnt["hack"] = {}
There're once some temperory steps during the deployment, like, we have to kill some processes which are wrongly occupying the CPUs 100%, etc.. But now we dont need those steps. I can remove this part from the deployment code.

2019-04-03 02:04 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +         "99: check NIC name.",
Currently we dont need 99 anymore, NIC name will always be checked before a deployment. I will remove it.

2019-04-03 02:06 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +    LOG.Info("!!! WARNING !!!: vbox is not tested in this version of script.")
Actually I have modified the argument "method" to only accept "kvm". So it's ok to leave it here.

2019-04-03 02:14 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +        print("Waiting ... %s seconds left\r" % str(left))
The reason I call print here is, I dont want this log into the logfile. This is just a user-friendly message to ease the users.

2019-04-03 02:15 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +    except Exception, error:
Will be corrected.

2019-04-03 02:18 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +            return 0
The DEBUG flag is only for me to debug the whole script, to check if all the steps can be finished with right sub-script name and log name, etc. So here, if DEBUG, no need to check the result, just return Success and let the script continue.

2019-04-03 02:20 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +                return int(result)
modified as "if result:".

2019-04-03 02:24 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +    LOG.Info("Please check the full system log.")
added the location of the system logs.

2019-04-03 02:26 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +                continue
added.

2019-04-03 02:26 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +    if 0 != result:
You are right, modified.

2019-04-03 02:27 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +with open(dplmnt["config"], 'r') as cfg:
I will modify in future.

2019-04-03 02:28 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +            LOG.Info("Step 3: Run \"sudo config_controller --kubernetes\" on controller")
If you dont use --autoiso, you can still config_controller by hand. I called this half-manual. The script can still help on the following provisioning.

2019-04-03 02:29 UTC, ychen2u commented on deployment/autodeploy/autodeploy.py
> +               " --kubernetes"
Sure. I will remove it.

2019-04-03 02:30 UTC, ychen2u commented on deployment/autodeploy/cleanupdeploy.py
> +desc = "EC Auto Deployment - Cleanup"
This is "Edge Computing", I will modify this to "StarlingX". Thanks for pointing this out.

2019-04-03 02:32 UTC, ychen2u commented on deployment/autodeploy/cleanupdeploy.py
> +def cmdhost(cmd, cwd=None, logfile=None, silent=False):
Yes, we are trying to do a refactor for this tool, will clean up the code with seperate modules for the public functions in future.

2019-04-03 02:33 UTC, ychen2u commented on deployment/autodeploy/openstack_logcheck.py
> +# Parse the following log and return the dict for vmname.
What do you mean for this? Would you please provide more details?

2019-04-03 02:35 UTC, ychen2u commented on deployment/autodeploy/prepare.sh
> +sudo ntpdate edgehost02.sh.intel.com
I will remove it.

2019-04-03 18:25 UTC, saulwold approved these changes
There are a few more items that I would like to see addressed, such as using ssh key's instead of the expect script (I will create an issue for this) and handling the sudo differently (via sudoers).  I think I also mentioned maybe using a different method for checking

2019-04-03 18:25 UTC, ericho commented on deployment/autodeploy/openstack_logcheck.py
> +# Parse the following log and return the dict for vmname.
For openstack commands it is possible to get a formatted output, [see here](https://docs.openstack.org/python-openstackclient/pike/contributor/humaninterfaceguide.html#machine-output-format). So, it would be more easy to parse a csv than the table form.

2019-04-03 18:26 UTC, ericho approved these changes

2019-04-03 18:28 UTC, merged